export const LOADING_SPINNER_STARTED = 'LOADING_SPINNER_STARTED';
export const LOADING_SPINNER_FINISHED = 'LOADING_SPINNER_FINISHED';

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
