export const GET_SINGLE_PROJECT = 'GET_SINGLE_PROJECT';

export const UPDATE_PROJECT_REQUEST = 'UPDATE_PROJECTS_REQUEST';
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS';
export const UPDATE_PROJECT_FAILED = 'UPDATE_PROJECT_FAILED';

export const DELETE_PROJECT_REQUEST = 'DELETE_PROJECTS_REQUEST';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAILED = 'DELETE_PROJECT_FAILED';

export const UPDATE_TAG_REQUEST = 'UPDATE_TAG_REQUEST';
export const UPDATE_TAG_SUCCESS = 'UPDATE_TAG_SUCCESS';
export const UPDATE_TAG_FAILED = 'UPDATE_TAG_FAILED';

export const REMOVE_TAG = 'REMOVE_TAG';

export const CLEAR_PROJECT_STATE = 'CLEAR_PROJECT_STATE';
